name: e_commerce

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

#----------{ packages }------------

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  lottie: ^3.5.1
  smooth_page_indicator: ^2.0.1
  get: ^4.7.3
  iconsax: ^0.0.8
  carousel_slider: ^5.1.2
  readmore: ^3.0.0
  firebase_core: ^4.15.0
  firebase_storage: ^13.6.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  fluttertoast: ^10.0.0
  get_storage: ^2.1.1
  connectivity_plus: ^7.3.1
  google_sign_in: ^7.2.0
  shimmer: ^4.0.0
  image_picker: ^1.2.3
  dio: ^5.11.1
  crypto: ^3.0.7
  cached_network_image: ^4.0.3
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #----------{ Assets }------------

  assets:
    - assets/images/
    - assets/animations/
    - assets/logo/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/banners/
    - assets/products/
    - assets/brands/
    - assets/products/

  #----------{ Fonts }------------

  fonts:
    - family: "Nunito"
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400

        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic

        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500

        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
