// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ZUzEpGoY85D6YSENL2m7SCOpTpvwzbI',
    appId: '1:433524117856:android:445cc7549ec8e1d2d9ce05',
    messagingSenderId: '433524117856',
    projectId: 'shopx-420cb',
    storageBucket: 'shopx-420cb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTTARy5plqgdNd0VnPKkX26eNn_6WngM',
    appId: '1:433524117856:ios:dd99427a636a9f5fd9ce05',
    messagingSenderId: '433524117856',
    projectId: 'shopx-420cb',
    storageBucket: 'shopx-420cb.firebasestorage.app',
    androidClientId: '433524117856-2l4tee32hajmci7b0f8nt2kbuo8i1050.apps.googleusercontent.com',
    iosClientId: '433524117856-j7kkqaaqerhi49a1blsr5lpgd92a4h50.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
